%% --------------- Create UIcontrols for Settings tab -------------------- %%
% Create panels
gui_data.panel_set_general = uipanel('Parent', gui_data.tab_settings,...
    'Title','1. General parameters',...
    'Position',[.02 .8 .96 .18],...
    'fontweight', 'bold',...
    'fontsize', gui_data.standard_font_size);
gui_data.panel_set_physio = uipanel('Parent', gui_data.tab_settings,...
    'Title','2. Physio processing parameters',...
    'Position',[.02 .01 .47 .77],...
    'fontweight', 'bold',...
    'fontsize', gui_data.standard_font_size);
gui_data.panel_set_new = uipanel('Parent', gui_data.tab_settings,...
    'Title','Other parameters',...
    'Position',[.51 .01 .47 .77],...
    'fontweight', 'bold',...
    'fontsize', gui_data.standard_font_size);

% Export Settings button:
gui_data.export_settings = uicontrol('Parent', gui_data.panel_set_general,...
    'Style', 'push',...
    'String', 'Export Settings', ...
    'Units', 'Normalized',...
    'Position', [0.8 0.06 0.18 0.225],...
    'CallBack', @export_settings, ...
    'UserData', 0,...
    'fontsize', gui_data.button_font_size);

%% PHYSIO PANEL SETTINGS FIELDS
gui_data.physio_save_dir = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','physio.save_dir ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.05 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_physio_save_dir = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','physio_out',...
'Units', 'Normalized',...
'Position', [ 0.25 0.05 0.2 0.025 ], ...
'CallBack', @editphysio_save_dir , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.log_files_sampling_interval = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','log_files.sampling_interval ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.085 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_log_files_sampling_interval = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.085 0.2 0.025 ], ...
'CallBack', @editlog_files_sampling_interval , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.log_files_relative_start_acquisition = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','log_files.relative_start_acquisition ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.12000000000000001 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_log_files_relative_start_acquisition = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','0',...
'Units', 'Normalized',...
'Position', [ 0.25 0.12000000000000001 0.2 0.025 ], ...
'CallBack', @editlog_files_relative_start_acquisition , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.log_files_align_scan = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','log_files.align_scan ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.155 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_log_files_align_scan = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','last',...
'Units', 'Normalized',...
'Position', [ 0.25 0.155 0.2 0.025 ], ...
'CallBack', @editlog_files_align_scan , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.sqpar_NslicesPerBeat = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','sqpar.NslicesPerBeat ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.19 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_sqpar_NslicesPerBeat = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.19 0.2 0.025 ], ...
'CallBack', @editsqpar_NslicesPerBeat , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.sqpar_time_slice_to_slice = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','sqpar.time_slice_to_slice ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.22499999999999998 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_sqpar_time_slice_to_slice = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.22499999999999998 0.2 0.025 ], ...
'CallBack', @editsqpar_time_slice_to_slice , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.sqpar_Nprep = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','sqpar.Nprep ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.26 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_sqpar_Nprep = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.26 0.2 0.025 ], ...
'CallBack', @editsqpar_Nprep , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.sync_nominal = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','sync.nominal ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.295 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_sync_nominal = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.295 0.2 0.025 ], ...
'CallBack', @editsync_nominal , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.auto_matched_min = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','auto_matched.min ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.33 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_auto_matched_min = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','0.4',...
'Units', 'Normalized',...
'Position', [ 0.25 0.33 0.2 0.025 ], ...
'CallBack', @editauto_matched_min , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.auto_matched_file = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','auto_matched.file ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.365 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_auto_matched_file = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','initial_cpulse_kRpeakfile.mat',...
'Units', 'Normalized',...
'Position', [ 0.25 0.365 0.2 0.025 ], ...
'CallBack', @editauto_matched_file , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.posthoc_cpulse_select_off = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','posthoc_cpulse_select.off ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.39999999999999997 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_posthoc_cpulse_select_off = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.39999999999999997 0.2 0.025 ], ...
'CallBack', @editposthoc_cpulse_select_off , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.model_output_multiple_regressors = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','model.output_multiple_regressors ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.435 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_model_output_multiple_regressors = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','retroicor_regressors.txt',...
'Units', 'Normalized',...
'Position', [ 0.25 0.435 0.2 0.025 ], ...
'CallBack', @editmodel_output_multiple_regressors , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.model_output_physio = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','model.output_physio ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.47 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_model_output_physio = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','physio.mat',...
'Units', 'Normalized',...
'Position', [ 0.25 0.47 0.2 0.025 ], ...
'CallBack', @editmodel_output_physio , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.model_orthogonalise = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','model.orthogonalise ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.505 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_model_orthogonalise = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','none',...
'Units', 'Normalized',...
'Position', [ 0.25 0.505 0.2 0.025 ], ...
'CallBack', @editmodel_orthogonalise , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.model_censor_unreliable_recording_intervals = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','model.censor_unreliable_recording_intervals ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.54 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_model_censor_unreliable_recording_intervals = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','false',...
'Units', 'Normalized',...
'Position', [ 0.25 0.54 0.2 0.025 ], ...
'CallBack', @editmodel_censor_unreliable_recording_intervals , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.order_c = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','order.c ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.5750000000000001 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_order_c = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','3',...
'Units', 'Normalized',...
'Position', [ 0.25 0.5750000000000001 0.2 0.025 ], ...
'CallBack', @editorder_c , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.order_r = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','order.r ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.6100000000000001 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_order_r = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','4',...
'Units', 'Normalized',...
'Position', [ 0.25 0.6100000000000001 0.2 0.025 ], ...
'CallBack', @editorder_r , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.order_cr = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','order.cr ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.645 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_order_cr = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','1',...
'Units', 'Normalized',...
'Position', [ 0.25 0.645 0.2 0.025 ], ...
'CallBack', @editorder_cr , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.rvt_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','rvt.no ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.68 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_rvt_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.68 0.2 0.025 ], ...
'CallBack', @editrvt_no , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.hrv_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','hrv.no ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.7150000000000001 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_hrv_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.7150000000000001 0.2 0.025 ], ...
'CallBack', @edithrv_no , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.noise_rois_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','noise_rois.no ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.75 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_noise_rois_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.75 0.2 0.025 ], ...
'CallBack', @editnoise_rois_no , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.movement_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','movement.no ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.785 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_movement_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.785 0.2 0.025 ], ...
'CallBack', @editmovement_no , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.other_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','other.no ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.8200000000000001 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_other_no = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','[]',...
'Units', 'Normalized',...
'Position', [ 0.25 0.8200000000000001 0.2 0.025 ], ...
'CallBack', @editother_no , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.verbose_level = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','verbose.level ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.8550000000000001 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_verbose_level = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','2',...
'Units', 'Normalized',...
'Position', [ 0.25 0.8550000000000001 0.2 0.025 ], ...
'CallBack', @editverbose_level , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.verbose_fig_output_file = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','verbose.fig_output_file ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.89 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_verbose_fig_output_file = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','physIO_figures.png',...
'Units', 'Normalized',...
'Position', [ 0.25 0.89 0.2 0.025 ], ...
'CallBack', @editverbose_fig_output_file , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.verbose_use_tabs = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','text',...
'String','verbose.use_tabs ',...
'Units', 'Normalized',...
'Position', [ 0.02 0.925 0.2 0.025 ], ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);

gui_data.edit_verbose_use_tabs = uicontrol('Parent', gui_data.panel_set_physio,...
'Style','edit',...
'String','false',...
'Units', 'Normalized',...
'Position', [ 0.25 0.925 0.2 0.025 ], ...
'CallBack', @editverbose_use_tabs , ...
'HorizontalAlignment', 'left',...
'fontsize', gui_data.small_font_size);